spring.application.name=cms
spring.datasource.url=jdbc:mysql://localhost:3306/church
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT properties
app.jwt.secret=THIS_IS_A_VERY_LONG_SECRET_KEY_12345678912345678
app.jwt.expMinutes=1440
app.jwt.refreshExpDays=7

# Frontend links (change later to your domain)
app.frontend.activateUrl=http://localhost:5173/activate
app.frontend.resetUrl=http://localhost:5173/reset